export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  paypalClientId: process.env.PAYPAL_CLIENT_ID ?? "",
  paypalSecretKey: process.env.PAYPAL_SECRET_KEY ?? "",
  paypalMode: process.env.PAYPAL_MODE ?? "sandbox",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: parseInt(process.env.SMTP_PORT ?? "587"),
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPassword: process.env.SMTP_PASSWORD ?? "",
  supportEmail: process.env.SUPPORT_EMAIL ?? "noreply@mail.eterbox.com",
  recaptchaSecretKey: process.env.RECAPTCHA_SECRET_KEY ?? "",
  adminContactEmail: process.env.ADMIN_CONTACT_EMAIL ?? "soporte.eterbox@gmail.com",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
};

